Repository clojure-lsp/clojure-lsp, pull requests merged in 2021-02, with the labels that each got.

#267 GraalVM build
  .github/workflows/release.yml
  .lsp/config.edn
  deps.edn
  docs/capabilities.md
  graalvm/jni-config.json
  graalvm/native-compile.sh
  graalvm/proxy-config.json
  graalvm/reflect-config.json
  graalvm/resource-config.json
  graalvm/run-tracing-config.sh
  project.clj
  resources/log4j.properties
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/db.clj
  src/clojure_lsp/feature/call_hierarchy.clj
  src/clojure_lsp/feature/code_actions.clj
  src/clojure_lsp/feature/completion.clj
  src/clojure_lsp/feature/diagnostics.clj
  src/clojure_lsp/feature/document_symbol.clj
  src/clojure_lsp/feature/refactor.clj
  src/clojure_lsp/feature/semantic_tokens.clj
  src/clojure_lsp/handlers.clj
  src/clojure_lsp/interop.clj
  src/clojure_lsp/main.clj
  src/clojure_lsp/nrepl.clj
  src/clojure_lsp/parser.clj
  src/clojure_lsp/producer.clj
  src/clojure_lsp/queries.clj
  src/clojure_lsp/refactor/edit.clj
  src/clojure_lsp/refactor/transform.clj
  src/clojure_lsp/shared.clj
  test/clojure_lsp/handlers_test.clj
  test/clojure_lsp/interop_test.clj
  test/clojure_lsp/parser_test.clj
  test/clojure_lsp/queries_test.clj
  test/clojure_lsp/test_helper.clj
Labels: critical, enhancement, graalvm, help wanted

#291 Add `clojure.java.io` for add-missing-libspec
  .gitignore
  src/clojure_lsp/refactor/transform.clj
Labels: enhancement

#295 Fix graalvm build during CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  integration-test/sample-test/deps.edn
  integration-test/sample-test/project.clj
Labels: graalvm

#300 Support keywords analysis with clj-kondo
  deps.edn
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/feature/completion.clj
  src/clojure_lsp/feature/rename.clj
  src/clojure_lsp/handlers.clj
  src/clojure_lsp/parser.clj
  src/clojure_lsp/queries.clj
  test/clojure_lsp/handlers_test.clj
Labels: enhancement

#306 [Docs] Add Scoop installation method for Windows
  README.md
Labels: documentation

#313 Add in some information about further VIM refactoring mappings
  docs/clients.md
Labels: documentation, vim

#325 Configurable db path with :sqlite-db-path
  deps.edn
  docs/settings.md
  src/clojure_lsp/db.clj
  test/clojure_lsp/db_test.clj
Labels: enhancement

#330 Add in Arch installation instructions
  docs/installation.md
Labels: documentation

#334 Improve did-change performance
  src/clojure_lsp/feature/file_management.clj
  src/clojure_lsp/main.clj
Labels: performance
