Repository clojure-lsp/clojure-lsp, pull requests merged in 2021-05, with the labels that each got.

#424 Process most of async client request after processing changes
  CHANGELOG.md
  src/clojure_lsp/feature/file_management.clj
  src/clojure_lsp/feature/semantic_tokens.clj
  src/clojure_lsp/handlers.clj
Labels: critical

#432 Fix reflect config for SublimeText
  resources/META-INF/native-image/clojure-lsp/clojure-lsp/reflect-config.json
Labels: graalvm

#436 Fix a bug in `feature.file-management/did-open`
  src/clojure_lsp/feature/file_management.clj
Labels: bug

#435 Improve performance for didOpen method
  CHANGELOG.md
  docs/settings.md
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/feature/diagnostics.clj
  src/clojure_lsp/feature/file_management.clj
  test/clojure_lsp/features/diagnostics_test.clj
Labels: critical, performance

#437 Fix uri->filename not fully decoding URI
  src/clojure_lsp/shared.clj
  test/clojure_lsp/features/code_actions_test.clj
  test/clojure_lsp/handlers_test.clj
  test/clojure_lsp/refactor/transform_test.clj
  test/clojure_lsp/shared_test.clj
Labels: bug
