Repository clojure-lsp/clojure-lsp, pull requests merged in 2021-01, with the labels that each got.

#231 Add version in server-info map
  .cljfmt.edn
  src/clojure_lsp/handlers.clj
Labels: enhancement

#233 Improve clean ns
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/refactor/transform.clj
  test/clojure_lsp/crawler_test.clj
  test/clojure_lsp/refactor/transform_test.clj
Labels: enhancement

#235 Improve "add missing namespace" code action
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/feature/code_actions.clj
  src/clojure_lsp/feature/refactor.clj
  src/clojure_lsp/refactor/transform.clj
  test/clojure_lsp/handlers_test.clj
  test/clojure_lsp/refactor/transform_test.clj
Labels: enhancement

#239 Support for Add missing import code action
  src/clojure_lsp/clojure_core.clj
  src/clojure_lsp/feature/code_actions.clj
  src/clojure_lsp/parser.clj
  src/clojure_lsp/refactor/transform.clj
  test/clojure_lsp/handlers_test.clj
  test/clojure_lsp/refactor/transform_test.clj
Labels: enhancement

#241 Fix classpath-cmd modification for Windows
  src/clojure_lsp/crawler.clj
Labels: bug

#243 Performance improvement
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/db.clj
  src/clojure_lsp/feature/code_actions.clj
  src/clojure_lsp/feature/references.clj
  src/clojure_lsp/parser.clj
  test/clojure_lsp/handlers_test.clj
  test/clojure_lsp/parser_test.clj
Labels: performance

#248 Use MkDocs to Generate Website Assets
  .github/workflows/docs.yml
  Makefile
  README.md
  docs/capabilities.md
  docs/clients.md
  docs/settings.md
  docs/troubleshooting.md
  mkdocs.yml
Labels: documentation

#251 Prevent orphaned server processes
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/main.clj
  src/clojure_lsp/shared.clj
Labels: enhancement

#253 Read .nrepl-port file
  src/clojure_lsp/main.clj
Labels: enhancement

#249 Support clean unused imports
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/refactor/transform.clj
  test/clojure_lsp/crawler_test.clj
  test/clojure_lsp/refactor/transform_test.clj
Labels: enhancement

#256 Add code lens resolve support
  deps.edn
  docs/capabilities.md
  src/clojure_lsp/feature/code_actions.clj
  src/clojure_lsp/feature/refactor.clj
  src/clojure_lsp/handlers.clj
  src/clojure_lsp/interop.clj
  src/clojure_lsp/main.clj
  src/clojure_lsp/refactor/transform.clj
  test/clojure_lsp/features/code_actions_test.clj
  test/clojure_lsp/handlers_test.clj
  test/clojure_lsp/refactor/transform_test.clj
Labels: enhancement, performance

#261 Use clj-kondo analysis instead of own parsing
  .clj-kondo/config.edn
  README.md
  deps.edn
  docs/settings.md
  docs/troubleshooting.md
  project.clj
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/db.clj
  src/clojure_lsp/feature/call_hierarchy.clj
  src/clojure_lsp/feature/code_actions.clj
  src/clojure_lsp/feature/completion.clj
  src/clojure_lsp/feature/definition.clj
  src/clojure_lsp/feature/diagnostics.clj
  src/clojure_lsp/feature/document_symbol.clj
  src/clojure_lsp/feature/hover.clj
  src/clojure_lsp/feature/refactor.clj
  src/clojure_lsp/feature/references.clj
  src/clojure_lsp/feature/semantic_tokens.clj
  src/clojure_lsp/handlers.clj
  src/clojure_lsp/main.clj
  src/clojure_lsp/parser.clj
  src/clojure_lsp/queries.clj
  src/clojure_lsp/refactor/transform.clj
  src/clojure_lsp/shared.clj
  test/clojure_lsp/crawler_test.clj
  test/clojure_lsp/features/call_hierarchy_test.clj
  test/clojure_lsp/features/code_actions_test.clj
  test/clojure_lsp/features/completion_test.clj
  test/clojure_lsp/features/references.clj
  test/clojure_lsp/features/semantic_tokens_test.clj
  test/clojure_lsp/handlers_test.clj
  test/clojure_lsp/parser_test.clj
  test/clojure_lsp/queries_test.clj
  test/clojure_lsp/refactor/transform_test.clj
  test/clojure_lsp/shared_test.clj
  test/clojure_lsp/test_helper.clj
Labels: critical, enhancement

#272 Fix shadow cljs classpath project spec
  src/clojure_lsp/crawler.clj
Labels: bug

#275 Fix hover range
  src/clojure_lsp/handlers.clj
Labels: bug

#277 include timestamp and PID in lsp logs
  resources/log4j.properties
  src/clojure_lsp/main.clj
Labels: enhancement

#278 clj-kondo batch analysis
  CHANGELOG.md
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/main.clj
Labels: performance
