Repository clojure-lsp/clojure-lsp, pull requests merged in 2021-06, with the labels that each got.

#439 Fix inconsistent URI encoding and path representation
  integration-test/integration/helper.clj
  src/clojure_lsp/config.clj
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/db.clj
  src/clojure_lsp/feature/call_hierarchy.clj
  src/clojure_lsp/feature/completion.clj
  src/clojure_lsp/feature/file_management.clj
  src/clojure_lsp/feature/rename.clj
  src/clojure_lsp/handlers.clj
  src/clojure_lsp/interop.clj
  src/clojure_lsp/main.clj
  src/clojure_lsp/shared.clj
  test/clojure_lsp/config_test.clj
  test/clojure_lsp/db_test.clj
  test/clojure_lsp/features/call_hierarchy_test.clj
  test/clojure_lsp/features/code_actions_test.clj
  test/clojure_lsp/features/completion_test.clj
  test/clojure_lsp/features/diagnostics_test.clj
  test/clojure_lsp/features/file_management_test.clj
  test/clojure_lsp/features/hover_test.clj
  test/clojure_lsp/features/rename_test.clj
  test/clojure_lsp/features/resolve_macro_test.clj
  test/clojure_lsp/features/semantic_tokens_test.clj
  test/clojure_lsp/features/signature_help_test.clj
  test/clojure_lsp/features/workspace_symbols_test.clj
  test/clojure_lsp/handlers_test.clj
  test/clojure_lsp/interop_test.clj
  test/clojure_lsp/queries_test.clj
  test/clojure_lsp/refactor/transform_test.clj
  test/clojure_lsp/shared_test.clj
  test/clojure_lsp/test_helper.clj
Labels: critical

#445 Scan deps.edn for source-paths
  CHANGELOG.md
  docs/settings.md
  src/clojure_lsp/code_lens.clj
  src/clojure_lsp/config.clj
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/interop.clj
  test/clojure_lsp/config_test.clj
  test/clojure_lsp/db_test.clj
  test/clojure_lsp/main_test.clj
Labels: enhancement

#455 clojure-lsp as API / CLI
  deps.edn
  docs/api.md
  integration-test/integration/api/clean_ns_test.clj
  integration-test/integration/lsp.clj
  integration-test/run-all.clj
  integration-test/sample-test/fixtures/api/clean_ns/a.clj
  integration-test/sample-test/src/api/clean_ns/a.clj
  integration-test/sample-test/src/api/clean_ns/b.clj
  mkdocs.yml
  src-java/clojure_lsp/ClojureExtensions.java
  src/clojure_lsp/api.clj
  src/clojure_lsp/client.clj
  src/clojure_lsp/crawler.clj
  src/clojure_lsp/feature/file_management.clj
  src/clojure_lsp/feature/hover.clj
  src/clojure_lsp/feature/refactor.clj
  src/clojure_lsp/feature/rename.clj
  src/clojure_lsp/handlers.clj
  src/clojure_lsp/internal_api.clj
  src/clojure_lsp/main.clj
  src/clojure_lsp/parser.clj
  src/clojure_lsp/producer.clj
  src/clojure_lsp/queries.clj
  src/clojure_lsp/server.clj
  src/clojure_lsp/shared.clj
  test/clojure_lsp/api_test.clj
  test/clojure_lsp/features/code_actions_test.clj
  test/clojure_lsp/features/completion_test.clj
  test/clojure_lsp/features/diagnostics_test.clj
  test/clojure_lsp/features/file_management_test.clj
  test/clojure_lsp/features/rename_test.clj
  test/clojure_lsp/features/resolve_macro_test.clj
  test/clojure_lsp/features/signature_help_test.clj
  test/clojure_lsp/features/workspace_symbols_test.clj
  test/clojure_lsp/server_test.clj
Labels: API, critical
