Repository clojure-lsp/clojure-lsp, pull requests merged in 2021-03, with the labels that each got.

#357 Fix issue where a full text replacement was not handled
  src/clojure_lsp/feature/file_management.clj
Labels: bug

#366 Update troubleshooting
  docs/troubleshooting.md
Labels: documentation

#383 Fix keyword rename
  integration-test/integration/rename_test.clj
  integration-test/sample-test/src/rename/a.clj
  integration-test/sample-test/src/rename/b.clj
  integration-test/sample-test/src/rename_single_a.clj
  integration-test/sample-test/src/rename_single_b.clj
  src/clojure_lsp/feature/rename.clj
  test/clojure_lsp/handlers_test.clj
Labels: enhancement

#387 Add support for Outgoing call hierarchy
  CHANGELOG.md
  Makefile
  docs/capabilities.md
  docs/features.md
  docs/images/features/call-hierarchy-incoming.png
  docs/images/features/call-hierarchy-outgoing.png
  docs/images/features/call-hierarchy.png
  resources/META-INF/native-image/clojure-lsp/clojure-lsp/reflect-config.json
  src/clojure_lsp/feature/call_hierarchy.clj
  src/clojure_lsp/feature/resolve_macro.clj
  src/clojure_lsp/feature/signature_help.clj
  src/clojure_lsp/handlers.clj
  src/clojure_lsp/interop.clj
  src/clojure_lsp/main.clj
  src/clojure_lsp/queries.clj
  src/clojure_lsp/refactor/edit.clj
  src/clojure_lsp/shared.clj
  test/clojure_lsp/features/call_hierarchy_test.clj
  test/clojure_lsp/refactor/edit_test.clj
Labels: enhancement
