Repository clojure-lsp/clojure-lsp, pull requests merged in 2021-04, with the labels that each got.

#397 Fix for duplicate edits in cljc keyword renaming
  CHANGELOG.md
  integration-test/integration/rename_test.clj
  integration-test/sample-test/src/rename/a.cljc
  integration-test/sample-test/src/rename/b.cljc
  src/clojure_lsp/queries.clj
  test/clojure_lsp/handlers_test.clj
Labels: bug

#402 Add in my configuration for neovim
  docs/clients.md
Labels: documentation

#404 Workspace symbols fuzzy matching to be more intuitive
  CHANGELOG.md
  deps.edn
  src/clojure_lsp/feature/workspace_symbols.clj
  test/clojure_lsp/features/workspace_symbols_test.clj
Labels: enhancement

#410 Render brew class with template. Add Linux support
  .github/workflows/release.yml
  CHANGELOG.md
  docs/installation.md
Labels: enhancement
