Repository clojure-lsp/clojure-lsp, pull requests merged in 2022-02, with the labels that each got.

#754 parallelize a part of `clean-ns!` via pmap
  CHANGELOG.md
  lib/src/clojure_lsp/internal_api.clj
Labels: performance, API

#756 Abort completion in comment
  CHANGELOG.md
  cli/integration-test/integration/completion_test.clj
  cli/integration-test/sample-test/src/sample_test/completion/a.clj
  lib/src/clojure_lsp/feature/completion.clj
  lib/test/clojure_lsp/features/completion_test.clj
Labels: performance, editor

#765 Ignore kondo config nested under the project root
  CHANGELOG.md
  lib/src/clojure_lsp/kondo.clj
Labels: bug

#772 Tidy require/import code actions and refactorings
  common-test/src/clojure_lsp/test_helper.clj
  lib/src/clojure_lsp/feature/add_missing_libspec.clj
  lib/src/clojure_lsp/feature/call_hierarchy.clj
  lib/src/clojure_lsp/feature/clean_ns.clj
  lib/src/clojure_lsp/feature/code_actions.clj
  lib/src/clojure_lsp/feature/completion.clj
  lib/src/clojure_lsp/feature/signature_help.clj
  lib/src/clojure_lsp/handlers.clj
  lib/src/clojure_lsp/parser.clj
  lib/src/clojure_lsp/refactor/transform.clj
  lib/test/clojure_lsp/feature/add_missing_libspec_test.clj
  lib/test/clojure_lsp/features/code_actions_test.clj
  lib/test/clojure_lsp/parser_test.clj
Labels: enhancement, performance
